name: 'Rebuild and Restart a Docker Container'
description: 'Test Github action for me that replaces a running docker container with an updated image'
inputs:
  imagename:
    description: 'Name of the docker image'
    required: false
    default: 'default-iName:latest'
  containername:
    description: 'Name of the docker container that gets deployed'
    required: false
    default: 'default-cName'
  restartpolicy:
    description: 'Docker restart policy for the container'
    required: false
    default: unless-stopped
runs:
    using: 'composite'
    steps:
        - run: |
            echo "image name: ${{inputs.imagename}}"
            echo "container name: ${{inputs.containername}}"
            echo "restart policy: ${{inputs.restartpolicy}}"
          shell: bash
        - run: $GITHUB_ACTION_PATH/entrypoint.sh
          env:
            imagename: ${{inputs.imagename}}
            containername: ${{inputs.containername}}
            restartpolicy: ${{inputs.restartpolicy}}
          shell: bash